### ISSUE TITLE
CircleCI /bin/bash: sudo: command not found

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-circleci#12]
It _should_ be possible to run `sudo` commands on CircleCI ...
see: https://circleci.com/blog/sudo-circleci-make-me-a-sandwich 🤔 

_However_ we are getting an error:
![image](https://user-images.githubusercontent.com/194400/41711833-efe01b88-7540-11e8-9e06-c9560263748f.png)
```sh
lrwxrwxrwx 1 root root 4 Nov  8  2014 /bin/sh -> dash
/bin/bash: sudo: command not found
Exited with code 127
```

![image](https://user-images.githubusercontent.com/194400/41711578-55900692-7540-11e8-9cbd-8d0a04d03257.png)
```sh
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
Exited with code 100
```

The _super_ annoying thing is that this works _flawlessly_ on ***one*** of our projects:
![image](https://user-images.githubusercontent.com/194400/41712631-eb38cbbe-7542-11e8-9d0c-807ebd9d66fc.png)

🙄 😖

**Comment by nelsonic** [comment]
solved by including the following lines in the `.circleci/config.yml` file:
```yaml
      # Use BASH instead of DASH! see: https://ubuntuforums.org/showthread.php?t=1932504
      - run: apt-get install -y sudo # https://discuss.circleci.com/t/sudo-command-not-found/14208/4
      - run: ls -al /bin/sh && sudo rm /bin/sh && sudo ln -s /bin/bash /bin/sh && ls -al /bin/sh
```
i.e. we have to _install_ `sudo` ...!
